improve env template

diff --git a/env.sh.template b/env.sh.template
--- a/env.sh.template
+++ b/env.sh.template
@@ -1,7 +1,8 @@
+[ AWS_ACCOUNT_ID = $(libaws aws-account) ] || { echo wrong account; exit 1; } # fail if not in the right account
+
 export AWS_DEFAULT_REGION=$(libaws aws-region)
 export PROJECT_NAME=APP
 export PROJECT_DOMAIN=APP.DOMAIN.com
 export PROJECT_DOMAIN_WEBSOCKET=ws-APP.DOMAIN.com
 export PROJECT_URL=https://$PROJECT_DOMAIN
 export PROJECT_BUCKET=DOMAIN-APP-bucket
-export PUBKEY_CONTENT=$(cat ~/.ssh/id_ed25519.pub 2>/dev/null || echo fake)
